# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: ocean
  theme_night: minimal
  font: cyberpunk
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    # twitter: 'adrigabzu'
  analytics:
    google_analytics: ''
  verification:
    google: ''

# Site header

header:
  navbar:
    blox: "navbar"
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    # notice: '© {year} Adrian G. Zucco. This work is licensed under {license}'
    notice: '© {year} Adrian G. Zucco.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Mon, 02 Jan 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: github-dark
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/adrigabzu/AGZweb'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comments:
    provider: 'utterances'
    commentable:
      post: true
      # book: true
      project: true
      publication: true
      event: true
    commento:
      url: ''
    utterances:
      repo: 'adrigabzu/AGZweb'
      issue_term: 'title'
      label: 'comments'
      theme: 'github-dark'
  # comment:
  #   provider: ''
  #   disqus:
  #     shortname: ''
  #     show_count: true
  #   commento:
  #     url: ''
  #   giscus:
  #     repo: ''
  #     repo_id: ''
  #     category: ''
  #     category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
